# Native development SDK for the Unity rendering bridge. Wrappers use their own release pipeline.
set(CMAKE_BUILD_TYPE Release CACHE STRING "Native SDK configuration")
set(CMAKE_CXX_STANDARD 17 CACHE STRING "Native SDK configuration")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Native SDK configuration")
set(BUILD_SHARED_LIBS ON CACHE BOOL "Native SDK configuration")
set(VTK_INSTALL_SDK ON CACHE BOOL "Install the native development package")
set(VTK_USE_64BIT_IDS ON CACHE BOOL "Native SDK ABI")
set(VTK_USE_FUTURE_BOOL OFF CACHE BOOL "Native SDK ABI")
set(VTK_USE_FUTURE_CONST OFF CACHE BOOL "Native SDK ABI")
set(VTK_DEBUG_LEAKS OFF CACHE BOOL "Native SDK ABI")
set(VTK_SMP_IMPLEMENTATION_TYPE Sequential CACHE STRING "Native SDK backend")
set(VTK_BUILD_ALL_MODULES OFF CACHE BOOL "Select the bridge module closure")
set(VTK_BUILD_TESTING OFF CACHE BOOL "Native SDK consumer is tested separately")
set(VTK_BUILD_EXAMPLES OFF CACHE BOOL "Native SDK configuration")
set(VTK_ENABLE_REMOTE_MODULES OFF CACHE BOOL "Native SDK configuration")
set(VTK_WRAP_PYTHON OFF CACHE BOOL "Native SDK configuration")
set(VTK_WRAP_JAVA OFF CACHE BOOL "Native SDK configuration")
set(VTK_WRAP_CSHARP OFF CACHE BOOL "Native SDK configuration")
foreach(group StandAlone Rendering Imaging Views Qt Web MPI Tk)
  set(VTK_GROUP_ENABLE_${group} DONT_WANT CACHE STRING "Select the bridge module closure")
endforeach()
foreach(module RenderingOpenGL2 RenderingVolumeOpenGL2 RenderingExternal ImagingSources FiltersSources IOImage)
  set(VTK_MODULE_ENABLE_VTK_${module} YES CACHE STRING "Native bridge dependency")
endforeach()
